[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
blonkfi_vaults = "3DKd236vw1D564UGVp8d4QFF9EL4HWkxCBqjj5zcoR2w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yudhishthra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://mainnet.helius-rpc.com/?api-key=e8d89710-2b92-45e9-8772-6b3ea43341ec"

[[test.validator.clone]]
address = "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"
