[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blonkfi_vaults = "3DKd236vw1D564UGVp8d4QFF9EL4HWkxCBqjj5zcoR2w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yudhishthra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
